version: "3"

services:
  e2l_gw_broker:
    image: e2l-gw-broker:v1.0.0
    ports:
      - "10883:1883"
    volumes:
      - ./e2l-gw-broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./e2l-gw-broker/data/:/mosquitto/data/
      - ./e2l-gw-broker/log/:/mosquitto/log/
    networks:
      - e2l_network

        #  pyspark_application:
        #    image: pyspark_image:1
        #    depends_on:
        #      - e2l_gw_broker
        #    env_file:
        #      - ".env.spark"
        #    networks:
        #      - e2l_network
        #
        #  e2l_parser:
        #    image: e2l-parser:v1.0.0
        #    depends_on:
        #      - e2l_gw_broker
        #    env_file:
        #      - ".env.parser"
        #    ports:
        #      - "1680:1680/udp"
        #      - "50052:50052"
        #    networks:
        #      - e2l_network

networks:
  e2l_network:
    external: true
