version: "3"

services:
  e2l_gw_broker:
    hostname: e2l-gw-broker-${GW_ID}
    image: e2l-gw-broker:v1.0.0
    ports:
      - "10883:1883"
    volumes:
      - ./e2l-gw-broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./e2l-gw-broker/data/:/mosquitto/data/
      - ./e2l-gw-broker/log/:/mosquitto/log/
    networks:
      - e2l_network

  pyspark_application:
    hostname: e2l-process-${GW_ID}
    image: e2l-process:v2.0.0
    depends_on:
      - e2l_gw_broker
    env_file:
      - ".env.spark"
    networks:
      - e2l_network

  e2l_parser:
    hostname: e2l-gw-${GW_ID}
    image: e2l-parser:v1.1.0
    depends_on:
      - e2l_gw_broker
    env_file:
      - ".env.parser"
    ports:
      - "1680:1680/udp"
      - "50052:50052"
    networks:
      - e2l_network

networks:
  e2l_network:
    name: e2l_network
    driver: overlay
    external: true
