version: "3"

services:
  e2l_gw_broker:
    hostname: e2l-gw-broker-${GW_ID}
    image: emqx/emqx:5.8.0
    container_name: e2l-gw-broker
    # environment:
    #   - "EMQX_NODE_NAME=emqx@e2l-gw-broker.e2l_network"
    # healthcheck:
    #   test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
    #   interval: 5s
    #   timeout: 25s
    #   retries: 5
    networks:
      - e2l_network
    ports:
      - 10893:1883
      - 8093:8083
      - 8094:8084
      - 18893:8883
      - 18093:18083
    volumes:
      - ./e2l-gw-broker/data/:/opt/emqx/data
      - ./e2l-gw-broker/log/:/opt/emqx/log

  e2l_process:
    hostname: e2l-process-${GW_ID}
    # image: ghcr.io/edge2lora/e2l-process:time-window-cp
    image: ghcr.io/edge2lora/e2l-process:hampel-load-balancing-12
    # volumes:
    #   - ./e2l-process/output_files/:/opt/bitnami/spark/output_files/
    depends_on:
      - e2l_gw_broker
    env_file:
      - ".env.process"
    networks:
      - e2l_network

  e2l_parser:
    hostname: e2l-gw-${GW_ID}
    image: ghcr.io/edge2lora/e2l-parser:load-balancing-12
    depends_on:
      - e2l_gw_broker
    env_file:
      - ".env.parser"
    ports:
      - "1680:1680/udp"
      - "50052:50052"
    networks:
      - e2l_network

networks:
  e2l_network:
    name: e2l_network
    driver: overlay
    external: true
